language: java
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/996f1afd70df12c9e77b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false