language: java
jdk:
  - oraclejdk8
env:
    - COMPONENTS=build-tools-22.0.1,android-22
before_install:
    # Install base Android SDK
    - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-1/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
    - source ~/.android-sdk-installer/env
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/996f1afd70df12c9e77b
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false